### ISSUE TITLE
Spelling in the text on site

### ISSUE THREAD

**Issue by JKorytko** [SPC-project/InvOpps#13]
Please correct word's spelling in text
-  "Вычисления" надо с одним н - в двух местах -в оглавлении и страничке.
- который предлагает все распределены контроля 
- В Марковских - два раза один абзац
- В Матрицах - произвидение
- Сортировка - ... проходит лист га?? за шагом
- Рунге Кутты??
  Please check all words and their spelling very carefully

**Comment by MKonovalow** [comment]
Поправил
